version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run lint 
      - run: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN --only hosting
