version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13.12.0
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run lint
            - run: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN --only hosting
workflows:
    build-and-test:
      jobs:
        - build-and-test